### ISSUE TITLE
License Attribution

### ISSUE THREAD

**Issue by vg** [serenity-frontstack/serenity-frontstack.github.io#3]
It looks like this project is based on [Michael Rose](https://github.com/mmistakes)'s [Minimal Mistakes](https://github.com/mmistakes/minimal-mistakes) theme, which is licensed under the MIT License. The MIT license requires proper attribution. Please provide proper attribution.

**Comment by DvdChavarri** [comment]
Noted and Updated.
Thanks for the remark.
